/*
 * SequentialSchedActionHelper.h
 *
 *  Created on: 2014Äê11ÔÂ8ÈÕ
 *      Author: Thoughtworks
 */

#ifndef SEQUENTIALSCHEDACTIONHELPER_H_
#define SEQUENTIALSCHEDACTIONHELPER_H_

#include "SchedAction/SequentialSchedAction.h"
#include "Common/RepeatMacros.h"
#include "DummySchedAction.h"
#include "TemplateDeclHelper.h"
#include <iostream>
using namespace std;

#define TYPENAME_ACTION(n) typename ACTION##n = DummySchedAction
#define DECL_TEMPLATE(n) typename ACTION##n
#define PUSHBACK(n) pushBackAction(&action##n);
#define ACTION(n) ACTION##n
#define ACTION_DECL(n) 	ACTION##n action##n;


#define DEF_PARTIAL_SEQUENTIAL_TEMPLATES(n)\
template <DECL_TEMPLATES(n)>\
class SEQUENTIAL__ <PARTIAL_TEMPLATES_##n(ACTION_PARTS, DUMMY_PARTS)>\
: public SequentialSchedAction{\
public:\
	SEQUENTIAL__(){\
		PUSHBACKS(n)\
	}\
private:\
	ACTION_DECLS(n)\
};\

#define DEF_GENERIC_SEQUENTIAL_TEMPLATES(n)\
template <DECL_TEMPLATES(n)>\
class SEQUENTIAL__ : public SequentialSchedAction{\
public:\
	SEQUENTIAL__(){\
		PUSHBACKS(n)\
	}\
private:\
	ACTION_DECLS(n)\
};


template <DEFAULT_TEMPLATES(15)>
class SEQUENTIAL__;

DEF_PARTIAL_SEQUENTIAL_TEMPLATES(1)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(2)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(3)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(4)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(5)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(6)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(7)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(8)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(9)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(10)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(11)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(12)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(13)
DEF_PARTIAL_SEQUENTIAL_TEMPLATES(14)

DEF_GENERIC_SEQUENTIAL_TEMPLATES(15)


#endif /* SEQUENTIALSCHEDACTIONHELPER_H_ */
